project:
  type: website

website:
  title: "Hyungjoo Han"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

  page-footer: 
    right: "&copy; 2025, Hyungjoo Han"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



